apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: udacity-capstone
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
      - image: rajatrawat88/myrepo:latest
        imagePullPolicy: Always
        name: udacity-capstone
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
          path: /
            port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1